# Generated by Django 3.0 on 2024-01-26 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.PositiveIntegerField(verbose_name="В граммах"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="used_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Раз использовано в рецепте"
            ),
        ),
        migrations.DeleteModel(
            name="RecipeIngredient",
        ),
        migrations.AddField(
            model_name="recipeproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="recipes.Product",
                verbose_name="Продукт",
            ),
        ),
        migrations.AddField(
            model_name="recipeproduct",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes",
                to="recipes.Recipe",
                verbose_name="Рецепта",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="recipeproduct",
            unique_together={("recipe", "product")},
        ),
    ]
